# Generated by Django 3.2.5 on 2021-07-22 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210722_0650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='cteate_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='cteate_date',
            new_name='created_date',
        ),
    ]
